import {createClient} from "@supabase/supabase-js";
const STUDENTI="https://studenti.org.rs/en/suss/",SUSS="https://suss.rs/";
const decode=(value:string)=>value.replaceAll("\\u00253D","=").replaceAll("\\/","/").replaceAll("\\n"," ").replaceAll("&quot;",'"').replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
export async function POST(request:Request){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!url||!key||!token)return Response.json({error:"Unauthorized"},{status:401});
 const client=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}}),{data:{user}}=await client.auth.getUser(token);if(!user)return Response.json({error:"Unauthorized"},{status:401});const{data:profile}=await client.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="admin")return Response.json({error:"Admin access required"},{status:403});
 const headers={"user-agent":"Terenski Kompas data sync (+https://suss.rs/)"};const[sussResponse,studentiResponse]=await Promise.all([fetch(SUSS,{headers}),fetch(STUDENTI,{headers})]);if(!sussResponse.ok||!studentiResponse.ok)return Response.json({error:"One or more public sources could not be reached"},{status:502});const[sussHtml,studentiHtml]=await Promise.all([sussResponse.text(),studentiResponse.text()]);
 const postUrls=[...new Set([...sussHtml.matchAll(/https:\/\/www\.instagram\.com\/p\/([A-Za-z0-9_-]+)\/embed/g)].map(m=>`https://www.instagram.com/p/${m[1]}/embed`))];const items:Record<string,unknown>[]=[];const autoImported=0;
 for(const sourceUrl of postUrls){const externalId=sourceUrl.split("/").at(-2)!;let text="";try{const html=await(await fetch(sourceUrl,{headers})).text();const caption=html.match(/"caption":\{"text":"((?:\\.|[^"\\])*)"/);text=caption?decode(caption[1]):""}catch{}items.push({id:`instagram:${externalId}`,source_url:sourceUrl,source_name:"suss.rs",kind:"historical_visit",extracted_text:text||null,status:"needs_review",last_seen_at:new Date().toISOString()})}
 const verification=studentiHtml.match(/<h3 id="how-to-recognize-us"[\s\S]*?<\/section>/i)?.[0];items.push({id:"studenti:verification-guide",source_url:STUDENTI,source_name:"studenti.org.rs",kind:"guideline",extracted_text:verification?decode(verification).slice(0,5000):null,status:"imported",last_seen_at:new Date().toISOString()});
 const{error}=await client.from("suss_ingestion_items").upsert(items,{onConflict:"id"});if(error)return Response.json({error:error.message},{status:400});
 return Response.json({sources:[STUDENTI,SUSS],historical_posts_found:postUrls.length,auto_imported_tour_stops:autoImported,review_queue:items.filter(x=>x.status==="needs_review").length,note:"Pins are created only after a location is verified; ambiguous social posts stay in review."});
}
