"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-location-assign-relative-destination */
import {useEffect,useState,type FormEvent,type ReactNode} from "react";import {ArrowLeft,Compass,KeyRound,LoaderCircle,LogOut,Mail,Save,ShieldCheck,UserRound} from "lucide-react";import {toast} from "sonner";import {AuthGate} from "@/components/auth-gate";import {EducationSelect} from "@/components/education-select";import {LanguageToggle,useLanguage} from "@/components/language-provider";import {Button} from "@/components/ui/button";import {Card} from "@/components/ui/card";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {Toaster} from "@/components/ui/sonner";import {getSupabase} from "@/lib/supabase/client";
type Profile={full_name:string;email:string|null;phone_number:string|null;assigned_region:string|null;university_id:string|null;faculty_id:string|null;preferred_language:"sr"|"en";role:string;approval_status:string};
export default function ProfilePage(){return <AuthGate><Settings/></AuthGate>}
function Settings(){const{t,language}=useLanguage(),[profile,setProfile]=useState<Profile|null>(null),[busy,setBusy]=useState(false),setup=typeof window!=="undefined"&&new URLSearchParams(location.search).get("setup")==="password";
useEffect(()=>{void(async()=>{const s=getSupabase()!,{data:{session}}=await s.auth.getSession();if(!session)return;const{data,error}=await s.from("profiles").select("full_name,email,phone_number,assigned_region,university_id,faculty_id,preferred_language,role,approval_status").eq("id",session.user.id).single();error?toast.error(error.message):setProfile(data as Profile)})()},[]);
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),{error}=await getSupabase()!.rpc("update_own_profile",{new_full_name:String(f.get("full_name")),new_phone:String(f.get("phone")),new_region:String(f.get("region")),new_university_id:String(f.get("university_id"))||null,new_faculty_id:String(f.get("faculty_id"))||null,new_language:language});error?toast.error(error.message):toast.success(t("Profil je sačuvan.","Profile saved."));setBusy(false)}
async function email(e:FormEvent<HTMLFormElement>){e.preventDefault();const{error}=await getSupabase()!.auth.updateUser({email:String(new FormData(e.currentTarget).get("email"))});error?toast.error(error.message):toast.success(t("Potvrdite novu adresu iz email poruke.","Confirm the new address from your email."))}
async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();const{error}=await getSupabase()!.auth.updateUser({password:String(new FormData(e.currentTarget).get("password")),data:{password_configured:true}});error?toast.error(error.message):(toast.success(t("Lozinka je postavljena.","Password set.")),history.replaceState({},"","/profile"))}
async function logout(){await getSupabase()!.auth.signOut();location.href="/login"}if(!profile)return <main className="setup-screen"><LoaderCircle className="spin"/></main>;
return <div className="settings-shell"><aside className="settings-sidebar"><a href="/" className="admin-brand"><span className="brand-mark"><Compass/></span><span><b>Terenski Kompas</b><small>{t("PODEŠAVANJA","SETTINGS")}</small></span></a><nav><a href="/"><ArrowLeft/>{t("Nazad na dashboard","Back to dashboard")}</a><a className="active" href="/profile"><UserRound/>{t("Profil i nalog","Profile & account")}</a></nav><button onClick={logout}><LogOut/>{t("Odjavi se","Log out")}</button></aside><main className="settings-main"><header><div><p className="eyebrow">{t("MOJ NALOG","MY ACCOUNT")}</p><h1>{t("Profil i podešavanja","Profile & settings")}</h1><p>{t("Upravljajte ličnim podacima i bezbednošću naloga.","Manage personal details and account security.")}</p></div><LanguageToggle compact/></header>{setup&&<div className="setup-password-banner"><KeyRound/><div><b>{t("Postavite lozinku","Set a password")}</b><p>{t("Kreirajte lozinku za direktnu prijavu sledeći put.","Create a password for direct sign-in next time.")}</p></div></div>}<div className="settings-grid"><Card className="settings-card"><Head icon={<UserRound/>} title={t("Lični podaci","Personal details")} text={`${profile.role.replaceAll("_"," ")} · ${profile.approval_status}`}/><form onSubmit={save}><Field label={t("Ime i prezime","Full name")}><Input name="full_name" defaultValue={profile.full_name} required/></Field><Field label={t("Telefon","Phone")}><Input name="phone" defaultValue={profile.phone_number??""}/></Field><Field label={t("Region","Region")}><Input name="region" defaultValue={profile.assigned_region??""}/></Field><EducationSelect defaultUniversity={profile.university_id??""} defaultFaculty={profile.faculty_id??""}/><Button disabled={busy}><Save/>{t("Sačuvaj profil","Save profile")}</Button></form></Card><Card className="settings-card"><Head icon={<ShieldCheck/>} title={t("Prijava i bezbednost","Sign-in & security")} text={t("Promene emaila zahtevaju potvrdu.","Email changes require confirmation.")}/><form onSubmit={email}><Field label="Email"><Input name="email" type="email" defaultValue={profile.email??""} required/></Field><Button variant="outline"><Mail/>{t("Promeni email","Change email")}</Button></form><form onSubmit={password} className="password-form"><Field label={t("Nova lozinka","New password")}><Input name="password" type="password" minLength={8} required/></Field><Button><KeyRound/>{setup?t("Postavi lozinku","Set password"):t("Promeni lozinku","Change password")}</Button></form></Card></div></main><Toaster richColors position="top-center"/></div>}
function Head({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="settings-card-head">{icon}<div><h2>{title}</h2><p>{text}</p></div></div>}function Field({label,children}:{label:string;children:ReactNode}){return <label><Label>{label}</Label>{children}</label>}
