"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-location-assign-relative-destination */

import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Compass, KeyRound, LoaderCircle, LogOut, Mail, Save, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { AuthGate } from "@/components/auth-gate";
import { LanguageToggle, useLanguage } from "@/components/language-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Toaster } from "@/components/ui/sonner";
import { getSupabase } from "@/lib/supabase/client";

type Profile={full_name:string;email:string|null;phone_number:string|null;assigned_region:string|null;faculty:string|null;preferred_language:"sr"|"en";role:string;approval_status:string};

export default function ProfilePage(){return <AuthGate><ProfileSettings/></AuthGate>}

function ProfileSettings(){
  const {t,language}=useLanguage(); const [profile,setProfile]=useState<Profile|null>(null); const [busy,setBusy]=useState(false);
  const setup=typeof window!=="undefined"&&new URLSearchParams(window.location.search).get("setup")==="password";
  useEffect(()=>{void(async()=>{const supabase=getSupabase()!;const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data,error}=await supabase.from("profiles").select("full_name,email,phone_number,assigned_region,faculty,preferred_language,role,approval_status").eq("id",session.user.id).single();if(error)toast.error(error.message);else setProfile(data as Profile)})()},[]);
  const saveProfile=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const {error}=await getSupabase()!.rpc("update_own_profile",{new_full_name:String(f.get("full_name")),new_phone:String(f.get("phone")),new_region:String(f.get("region")),new_faculty:String(f.get("faculty")),new_language:language});if(error)toast.error(t("Profil nije sačuvan.","Profile was not saved."),{description:error.message});else toast.success(t("Profil je sačuvan.","Profile saved."));setBusy(false)};
  const saveEmail=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const email=String(new FormData(e.currentTarget).get("email"));const {error}=await getSupabase()!.auth.updateUser({email});if(error)toast.error(error.message);else toast.success(t("Potvrdi novu adresu preko poruke koju smo poslali.","Confirm the new address from the email we sent."));setBusy(false)};
  const savePassword=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const password=String(new FormData(e.currentTarget).get("password"));const {error}=await getSupabase()!.auth.updateUser({password,data:{password_configured:true}});if(error)toast.error(error.message);else{toast.success(t("Lozinka je postavljena.","Password set."));history.replaceState({},"","/profile")}setBusy(false)};
  const logout=async()=>{await getSupabase()!.auth.signOut();location.href="/login"};
  if(!profile)return <main className="setup-screen"><LoaderCircle className="spin"/></main>;
  return <div className="settings-shell"><aside className="settings-sidebar"><a href="/" className="admin-brand"><span className="brand-mark"><Compass/></span><span><b>Terenski Kompas</b><small>{t("PODEŠAVANJA","SETTINGS")}</small></span></a><nav><a href="/"><ArrowLeft/>{t("Nazad na dashboard","Back to dashboard")}</a><a className="active" href="/profile"><UserRound/>{t("Profil i nalog","Profile & account")}</a></nav><button onClick={logout}><LogOut/>{t("Odjavi se","Log out")}</button></aside><main className="settings-main"><header><div><p className="eyebrow">{t("MOJ NALOG","MY ACCOUNT")}</p><h1>{t("Profil i podešavanja","Profile & settings")}</h1><p>{t("Upravljaj ličnim podacima i bezbednošću naloga.","Manage personal details and account security.")}</p></div><LanguageToggle compact/></header>{setup&&<div className="setup-password-banner"><KeyRound/><div><b>{t("Postavi lozinku za svoj nalog","Set a password for your account")}</b><p>{t("Prijavljeni ste magic linkom. Kreirajte lozinku da biste sledeći put mogli da se prijavite i bez email linka.","You signed in with a magic link. Create a password so you can also sign in directly next time.")}</p></div></div>}<div className="settings-grid"><section className="settings-card"><div className="settings-card-head"><UserRound/><div><h2>{t("Lični podaci","Personal details")}</h2><p>{profile.role.replaceAll("_"," ")} · {profile.approval_status}</p></div></div><form onSubmit={saveProfile}><Field label={t("Ime i prezime","Full name")}><Input name="full_name" defaultValue={profile.full_name} required/></Field><Field label={t("Telefon","Phone")}><Input name="phone" defaultValue={profile.phone_number??""}/></Field><Field label={t("Region","Region")}><Input name="region" defaultValue={profile.assigned_region??""}/></Field><Field label={t("Fakultet","Faculty")}><Input name="faculty" defaultValue={profile.faculty??""}/></Field><Button disabled={busy}><Save/>{t("Sačuvaj profil","Save profile")}</Button></form></section><section className="settings-card"><div className="settings-card-head"><ShieldCheck/><div><h2>{t("Prijava i bezbednost","Sign-in & security")}</h2><p>{t("Promene emaila zahtevaju potvrdu.","Email changes require confirmation.")}</p></div></div><form onSubmit={saveEmail}><Field label={t("Email adresa","Email address")}><Input name="email" type="email" defaultValue={profile.email??""} required/></Field><Button variant="outline" disabled={busy}><Mail/>{t("Promeni email","Change email")}</Button></form><form onSubmit={savePassword} className="password-form"><Field label={t("Nova lozinka","New password")}><Input name="password" type="password" minLength={8} required/></Field><Button disabled={busy}><KeyRound/>{setup?t("Postavi lozinku","Set password"):t("Promeni lozinku","Change password")}</Button></form></section></div></main><Toaster richColors position="top-center"/></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><Label>{label}</Label>{children}</label>}
