"use client";
import {useEffect,useMemo,useState} from "react";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {getSupabase} from "@/lib/supabase/client";
import {useLanguage} from "@/components/language-provider";
type University={id:string;name_sr:string;name_en:string};type Faculty={id:string;university_id:string;name_sr:string;name_en:string};
export function EducationSelect({defaultUniversity="",defaultFaculty="",required=false}:{defaultUniversity?:string;defaultFaculty?:string;required?:boolean}){const{t,language}=useLanguage(),[universities,setUniversities]=useState<University[]>([]),[faculties,setFaculties]=useState<Faculty[]>([]),[university,setUniversity]=useState(defaultUniversity),[faculty,setFaculty]=useState(defaultFaculty);
useEffect(()=>{void(async()=>{const s=getSupabase();if(!s)return;const[u,f]=await Promise.all([s.from("universities").select("id,name_sr,name_en").order("display_order"),s.from("faculties").select("id,university_id,name_sr,name_en").order("name_sr")]);setUniversities((u.data??[])as University[]);setFaculties((f.data??[])as Faculty[])})()},[]);const options=useMemo(()=>faculties.filter(f=>f.university_id===university),[faculties,university]);
return <><label><Label>{t("Univerzitet (opciono)","University (optional)")}</Label><Select name="university_id" value={university||"none"} onValueChange={v=>{setUniversity(v==="none"?"":v);setFaculty("")}} required={required}><SelectTrigger><SelectValue placeholder={t("Izaberi univerzitet","Select university")}/></SelectTrigger><SelectContent><SelectItem value="none">{t("Nisam povezan/a sa univerzitetom","Not affiliated with a university")}</SelectItem>{universities.map(u=><SelectItem key={u.id} value={u.id}>{language==="sr"?u.name_sr:u.name_en}</SelectItem>)}</SelectContent></Select></label><label><Label>{t("Fakultet / članica (opciono)","Faculty / member institution (optional)")}</Label><Select name="faculty_id" value={faculty||"none"} onValueChange={v=>setFaculty(v==="none"?"":v)} disabled={!university}><SelectTrigger><SelectValue placeholder={t("Izaberi fakultet","Select faculty")}/></SelectTrigger><SelectContent><SelectItem value="none">{t("Bez fakulteta","No faculty")}</SelectItem>{options.map(f=><SelectItem key={f.id} value={f.id}>{language==="sr"?f.name_sr:f.name_en}</SelectItem>)}</SelectContent></Select></label></>}
