"use client";
import {useEffect,useState} from "react";
import {Check,ChevronsUpDown,LoaderCircle,MapPin} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Command,CommandEmpty,CommandGroup,CommandInput,CommandItem,CommandList} from "@/components/ui/command";
import {Popover,PopoverContent,PopoverTrigger} from "@/components/ui/popover";
import {getSupabase} from "@/lib/supabase/client";
import {useLanguage} from "@/components/language-provider";
type Location={id:number;name:string;municipality:string|null;district:string|null;latitude:number;longitude:number};
export function LocationSelect({name="location_id",textName="city_village",defaultId,defaultText="",required=false,onSelect}:{name?:string;textName?:string;defaultId?:number|null;defaultText?:string;required?:boolean;onSelect?:(value:Location)=>void}){
 const{t}=useLanguage(),[open,setOpen]=useState(false),[query,setQuery]=useState(defaultText),[selected,setSelected]=useState<Location|null>(defaultId&&defaultText?{id:defaultId,name:defaultText,municipality:null,district:null,latitude:0,longitude:0}:null),[rows,setRows]=useState<Location[]>([]),[loading,setLoading]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{void(async()=>{const s=getSupabase();if(!s||query.trim().length<2){setRows([]);return}setLoading(true);const{data}=await s.rpc("search_serbian_locations",{search_query:query.trim(),result_limit:50});setRows((data??[]) as Location[]);setLoading(false)})()},220);return()=>clearTimeout(timer)},[query]);
 const label=selected?[selected.name,selected.municipality,selected.district].filter(Boolean).join(" · "):defaultText||t("Izaberi grad, opštinu ili selo","Select a city, municipality, or village");
 return <><input type="hidden" name={name} value={selected?.id??""}/><input type="hidden" name={textName} value={selected?.name??""} required={required}/><Popover open={open} onOpenChange={setOpen}><PopoverTrigger render={<Button type="button" variant="outline" className="location-trigger" aria-label={t("Izaberi lokaciju","Select location")}/>}><MapPin/><span>{label}</span><ChevronsUpDown/></PopoverTrigger><PopoverContent className="location-popover" align="start"><Command shouldFilter={false}><CommandInput value={query} onValueChange={setQuery} placeholder={t("Počni da kucaš naziv mesta…","Start typing a place name…")}/><CommandList>{loading?<div className="location-loading"><LoaderCircle className="spin"/></div>:<><CommandEmpty>{query.length<2?t("Unesi najmanje 2 slova.","Enter at least 2 letters."):t("Nema rezultata.","No results.")}</CommandEmpty><CommandGroup>{rows.map(item=><CommandItem key={item.id} value={String(item.id)} onSelect={()=>{setSelected(item);setQuery(item.name);setOpen(false);onSelect?.(item)}}><Check className={selected?.id===item.id?"visible":"invisible"}/><span><b>{item.name}</b><small>{[item.municipality,item.district].filter(Boolean).join(" · ")}</small></span></CommandItem>)}</CommandGroup></>}</CommandList></Command></PopoverContent></Popover></>;
}
