create type public.user_role as enum ('admin','coordinator','canvasser','poll_watcher');
create type public.door_status as enum ('visited_supporter','visited_neutral','visited_hostile','not_home','refused');
create type public.incident_severity as enum ('low','medium','critical');
create type public.incident_status as enum ('pending_review','verified','dismissed','escalated_to_legal');
create table public.profiles (id uuid references auth.users primary key,full_name text not null,phone_number text unique not null,role public.user_role default 'canvasser',assigned_region text default 'Belgrade',created_at timestamptz default now());
create table public.canvassing_points (id uuid primary key default gen_random_uuid(),canvasser_id uuid references public.profiles(id) on delete set null,latitude double precision not null,longitude double precision not null,address_street text,address_number text,city_village text not null,status public.door_status not null,notes text,follow_up_requested boolean default false,created_at timestamptz default now());
create table public.recruits (id uuid primary key default gen_random_uuid(),recruiter_id uuid references public.profiles(id),full_name text not null,phone_number text not null,email text,city_village text not null,interested_in_poll_watching boolean default false,created_at timestamptz default now());
create table public.incidents (id uuid primary key default gen_random_uuid(),reporter_id uuid references public.profiles(id),polling_station_number text not null,municipality text not null,title text not null,description text not null,severity public.incident_severity default 'medium',status public.incident_status default 'pending_review',media_urls text[],latitude double precision,longitude double precision,created_at timestamptz default now());
create table public.donations (id uuid primary key default gen_random_uuid(),canvasser_id uuid references public.profiles(id),amount_rsd numeric(10,2) not null check (amount_rsd > 0),donor_name text default 'Anonymous',payment_method text default 'NBS_IPS_QR',transaction_reference text unique,created_at timestamptz default now());
alter table public.profiles enable row level security;
alter table public.canvassing_points enable row level security;
alter table public.recruits enable row level security;
alter table public.incidents enable row level security;
alter table public.donations enable row level security;
create policy "profiles read own or admin" on public.profiles for select using (auth.uid()=id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','coordinator')));
create policy "field staff insert points" on public.canvassing_points for insert with check (auth.uid()=canvasser_id);
create policy "field staff read own points" on public.canvassing_points for select using (auth.uid()=canvasser_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','coordinator')));
create policy "recruiters insert recruits" on public.recruits for insert with check (auth.uid()=recruiter_id);
create policy "watchers insert incidents" on public.incidents for insert with check (auth.uid()=reporter_id);
create policy "incident visibility" on public.incidents for select using (auth.uid()=reporter_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','coordinator')));
create policy "field staff insert donations" on public.donations for insert with check (auth.uid()=canvasser_id);
