create table if not exists public.universities (
  id uuid primary key default gen_random_uuid(), slug text not null unique,
  name_sr text not null, name_en text not null, display_order integer not null default 0,
  active boolean not null default true
);
create table if not exists public.faculties (
  id uuid primary key default gen_random_uuid(), university_id uuid not null references public.universities(id) on delete cascade,
  name_sr text not null, name_en text not null, active boolean not null default true,
  unique(university_id,name_sr)
);
alter table public.universities enable row level security; alter table public.faculties enable row level security;
grant select on public.universities,public.faculties to anon,authenticated;
drop policy if exists "public reads universities" on public.universities; create policy "public reads universities" on public.universities for select using(active);
drop policy if exists "public reads faculties" on public.faculties; create policy "public reads faculties" on public.faculties for select using(active);

insert into public.universities(slug,name_sr,name_en,display_order) values
('beograd','Univerzitet u Beogradu','University of Belgrade',1),('novi-sad','Univerzitet u Novom Sadu','University of Novi Sad',2),('nis','Univerzitet u Nišu','University of Niš',3),('kragujevac','Univerzitet u Kragujevcu','University of Kragujevac',4),('novi-pazar-drzavni','Državni univerzitet u Novom Pazaru','State University of Novi Pazar',5),('umetnosti-beograd','Univerzitet umetnosti u Beogradu','University of Arts in Belgrade',6),('odbrane','Univerzitet odbrane u Beogradu','University of Defense',7),('kpu','Kriminalističko-policijski univerzitet','University of Criminal Investigation and Police Studies',8),('singidunum','Univerzitet Singidunum','Singidunum University',9),('metropolitan','Univerzitet Metropolitan','Metropolitan University',10),('privredna-akademija','Univerzitet Privredna akademija','University Business Academy',11),('union','Univerzitet Union','Union University',12),('union-nikola-tesla','Univerzitet Union - Nikola Tesla','Union - Nikola Tesla University',13),('educons','Educons Univerzitet','Educons University',14),('alfa-bk','Alfa BK Univerzitet','Alfa BK University',15),('megatrend','Megatrend Univerzitet','Megatrend University',16),('novi-pazar-internacionalni','Internacionalni univerzitet u Novom Pazaru','International University of Novi Pazar',17),('mb','Univerzitet MB','MB University',18),('evropski','Evropski Univerzitet','European University',19)
on conflict(slug) do update set name_sr=excluded.name_sr,name_en=excluded.name_en,display_order=excluded.display_order,active=true;

with seed(university_slug,name_sr,name_en) as (values
('beograd','Arhitektonski fakultet','Faculty of Architecture'),('beograd','Biološki fakultet','Faculty of Biology'),('beograd','Ekonomski fakultet','Faculty of Economics'),('beograd','Elektrotehnički fakultet','School of Electrical Engineering'),('beograd','Fakultet bezbednosti','Faculty of Security Studies'),('beograd','Fakultet organizacionih nauka','Faculty of Organizational Sciences'),('beograd','Fakultet političkih nauka','Faculty of Political Sciences'),('beograd','Fakultet sporta i fizičkog vaspitanja','Faculty of Sport and Physical Education'),('beograd','Farmaceutski fakultet','Faculty of Pharmacy'),('beograd','Filološki fakultet','Faculty of Philology'),('beograd','Filozofski fakultet','Faculty of Philosophy'),('beograd','Fizički fakultet','Faculty of Physics'),('beograd','Geografski fakultet','Faculty of Geography'),('beograd','Građevinski fakultet','Faculty of Civil Engineering'),('beograd','Hemijski fakultet','Faculty of Chemistry'),('beograd','Mašinski fakultet','Faculty of Mechanical Engineering'),('beograd','Matematički fakultet','Faculty of Mathematics'),('beograd','Medicinski fakultet','Faculty of Medicine'),('beograd','Poljoprivredni fakultet','Faculty of Agriculture'),('beograd','Pravni fakultet','Faculty of Law'),('beograd','Pravoslavni bogoslovski fakultet','Faculty of Orthodox Theology'),('beograd','Rudarsko-geološki fakultet','Faculty of Mining and Geology'),('beograd','Saobraćajni fakultet','Faculty of Transport and Traffic Engineering'),('beograd','Stomatološki fakultet','Faculty of Dental Medicine'),('beograd','Šumarski fakultet','Faculty of Forestry'),('beograd','Tehnološko-metalurški fakultet','Faculty of Technology and Metallurgy'),('beograd','Učiteljski fakultet','Teacher Education Faculty'),('beograd','Veterinarski fakultet','Faculty of Veterinary Medicine'),
('novi-sad','Akademija umetnosti Novi Sad','Academy of Arts Novi Sad'),('novi-sad','Ekonomski fakultet u Subotici','Faculty of Economics in Subotica'),('novi-sad','Fakultet tehničkih nauka','Faculty of Technical Sciences'),('novi-sad','Filozofski fakultet','Faculty of Philosophy'),('novi-sad','Građevinski fakultet Subotica','Faculty of Civil Engineering Subotica'),('novi-sad','Medicinski fakultet','Faculty of Medicine'),('novi-sad','Pedagoški fakultet u Somboru','Faculty of Education in Sombor'),('novi-sad','Poljoprivredni fakultet','Faculty of Agriculture'),('novi-sad','Pravni fakultet','Faculty of Law'),('novi-sad','Prirodno-matematički fakultet','Faculty of Sciences'),('novi-sad','Tehnički fakultet Mihajlo Pupin','Technical Faculty Mihajlo Pupin'),('novi-sad','Tehnološki fakultet Novi Sad','Faculty of Technology Novi Sad'),('novi-sad','Učiteljski fakultet na mađarskom nastavnom jeziku','Hungarian Language Teacher Training Faculty'),
('nis','Ekonomski fakultet','Faculty of Economics'),('nis','Elektronski fakultet','Faculty of Electronic Engineering'),('nis','Fakultet sporta i fizičkog vaspitanja','Faculty of Sport and Physical Education'),('nis','Fakultet umetnosti','Faculty of Arts'),('nis','Filozofski fakultet','Faculty of Philosophy'),('nis','Građevinsko-arhitektonski fakultet','Faculty of Civil Engineering and Architecture'),('nis','Mašinski fakultet','Faculty of Mechanical Engineering'),('nis','Medicinski fakultet','Faculty of Medicine'),('nis','Pravni fakultet','Faculty of Law'),('nis','Prirodno-matematički fakultet','Faculty of Sciences'),('nis','Tehnološki fakultet u Leskovcu','Faculty of Technology in Leskovac'),('nis','Učiteljski fakultet u Vranju','Teacher Training Faculty in Vranje'),
('kragujevac','Agronomski fakultet u Čačku','Faculty of Agronomy in Čačak'),('kragujevac','Ekonomski fakultet','Faculty of Economics'),('kragujevac','Fakultet inženjerskih nauka','Faculty of Engineering'),('kragujevac','Fakultet medicinskih nauka','Faculty of Medical Sciences'),('kragujevac','Fakultet pedagoških nauka u Jagodini','Faculty of Education in Jagodina'),('kragujevac','Fakultet tehničkih nauka u Čačku','Faculty of Technical Sciences in Čačak'),('kragujevac','Filološko-umetnički fakultet','Faculty of Philology and Arts'),('kragujevac','Hotelijerstvo i turizam u Vrnjačkoj Banji','Faculty of Hotel Management and Tourism'),('kragujevac','Pedagoški fakultet u Užicu','Faculty of Education in Užice'),('kragujevac','Pravni fakultet','Faculty of Law'),('kragujevac','Prirodno-matematički fakultet','Faculty of Science'),
('umetnosti-beograd','Fakultet dramskih umetnosti','Faculty of Dramatic Arts'),('umetnosti-beograd','Fakultet likovnih umetnosti','Faculty of Fine Arts'),('umetnosti-beograd','Fakultet muzičke umetnosti','Faculty of Music'),('umetnosti-beograd','Fakultet primenjenih umetnosti','Faculty of Applied Arts'),
('odbrane','Medicinski fakultet Vojnomedicinske akademije','Medical Faculty of the Military Medical Academy'),('odbrane','Vojna akademija','Military Academy'),
('kpu','Kriminalističko-policijski univerzitet','University programs'),('novi-pazar-drzavni','Državni univerzitet u Novom Pazaru','Integrated university departments'),
('singidunum','Univerzitet Singidunum','Singidunum University programs'),('metropolitan','Univerzitet Metropolitan','Metropolitan University programs'),('privredna-akademija','Univerzitet Privredna akademija','University Business Academy programs'),('union','Univerzitet Union','Union University programs'),('union-nikola-tesla','Univerzitet Union - Nikola Tesla','Union - Nikola Tesla programs'),('educons','Educons Univerzitet','Educons University programs'),('alfa-bk','Alfa BK Univerzitet','Alfa BK University programs'),('megatrend','Megatrend Univerzitet','Megatrend University programs'),('novi-pazar-internacionalni','Internacionalni univerzitet u Novom Pazaru','International University programs'),('mb','Univerzitet MB','MB University programs'),('evropski','Evropski Univerzitet','European University programs'))
insert into public.faculties(university_id,name_sr,name_en)
select u.id,s.name_sr,s.name_en from seed s join public.universities u on u.slug=s.university_slug
on conflict(university_id,name_sr) do update set name_en=excluded.name_en,active=true;

alter table public.profiles add column if not exists university_id uuid references public.universities(id);
alter table public.profiles add column if not exists faculty_id uuid references public.faculties(id);
alter table public.recruits add column if not exists university_id uuid references public.universities(id);
alter table public.recruits add column if not exists faculty_id uuid references public.faculties(id);

create table if not exists public.tour_stops(id uuid primary key default gen_random_uuid(),date date not null,municipality text not null,location_name text not null,status text not null default 'scheduled' check(status in('scheduled','in_progress','completed','cancelled')),latitude double precision,longitude double precision,notes text,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
alter table public.tour_stops enable row level security; grant select on public.tour_stops to authenticated; grant insert,update,delete on public.tour_stops to authenticated;
create policy "approved users read tour stops" on public.tour_stops for select to authenticated using(public.is_approved_user()); create policy "coordinators manage tour stops" on public.tour_stops for all to authenticated using(public.is_admin_or_coordinator()) with check(public.is_admin_or_coordinator());

create table if not exists public.website_leads(id uuid primary key default gen_random_uuid(),full_name text not null,email text not null,phone_number text,city_village text,university_id uuid references public.universities(id),faculty_id uuid references public.faculties(id),interested_in_poll_watching boolean not null default false,status text not null default 'new' check(status in('new','reviewed','converted','rejected')),notes text,created_at timestamptz not null default now(),reviewed_by uuid references public.profiles(id),reviewed_at timestamptz);
alter table public.website_leads enable row level security; grant insert on public.website_leads to anon,authenticated; grant select,update on public.website_leads to authenticated;
create policy "public submits website leads" on public.website_leads for insert to anon,authenticated with check(status='new' and reviewed_by is null); create policy "admins read website leads" on public.website_leads for select to authenticated using(public.is_admin());
create or replace function public.admin_review_website_lead(target_id uuid,new_status text) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'Admin access required'; end if; if new_status not in('reviewed','converted','rejected') then raise exception 'Invalid status'; end if; update public.website_leads set status=new_status,reviewed_by=auth.uid(),reviewed_at=now() where id=target_id; end $$; grant execute on function public.admin_review_website_lead(uuid,text) to authenticated;

create table if not exists public.field_documents(id uuid primary key default gen_random_uuid(),slug text not null unique,title_sr text not null,title_en text not null,content_sr text not null,content_en text not null,category text not null default 'guideline',display_order integer not null default 0,active boolean not null default true,updated_at timestamptz not null default now());
alter table public.field_documents enable row level security; grant select on public.field_documents to authenticated; create policy "approved users read field docs" on public.field_documents for select to authenticated using(public.is_approved_user());
insert into public.field_documents(slug,title_sr,title_en,content_sr,content_en,category,display_order) values
('verify-identity','Provera identiteta volontera','Volunteer identity verification','Nosite zvaničnu akreditaciju. Predstavite se imenom i timom. Nikada ne fotografišite lične dokumente građana i ne zapisujte JMBG.','Carry official accreditation. Introduce yourself and your team. Never photograph identity documents or record personal identification numbers.','verification',1),
('field-safety','Bezbednost na terenu','Field safety','Radite u paru kada je moguće. Obavestite koordinatora o ruti. Ne ulazite u prostor ako se ne osećate bezbedno. U hitnom slučaju pozovite 112.','Work in pairs where possible. Share your route with the coordinator. Do not enter a space if you feel unsafe. Call 112 in an emergency.','safety',2),
('data-privacy','Zaštita podataka','Data protection','Beležite samo podatke potrebne za terenski rad. Ne delite izvoze, fotografije ni kontakt podatke van odobrenih kanala SUSS-a.','Record only data needed for field work. Do not share exports, photos, or contact details outside approved SUSS channels.','privacy',3),
('incident-protocol','Protokol za incidente','Incident protocol','Sačuvajte bezbednu udaljenost, zabeležite proverljive činjenice, lokaciju i vreme. Ne ulazite u raspravu i odmah eskalirajte kritične slučajeve koordinatoru.','Keep a safe distance and record verifiable facts, location, and time. Do not confront anyone; escalate critical cases to the coordinator immediately.','safety',4)
on conflict(slug) do update set title_sr=excluded.title_sr,title_en=excluded.title_en,content_sr=excluded.content_sr,content_en=excluded.content_en,category=excluded.category,display_order=excluded.display_order,active=true;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare lead_status text;
begin
  select status into lead_status from public.website_leads where lower(email)=lower(new.email) and status='converted' order by reviewed_at desc limit 1;
  insert into public.profiles(id,full_name,email,phone_number,role,approval_status,university_id,faculty_id)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1),new.phone,'Volunteer'),new.email,new.phone,'canvasser',case when lead_status='converted' then 'approved'::public.profile_approval_status else 'pending'::public.profile_approval_status end,nullif(new.raw_user_meta_data->>'university_id','')::uuid,nullif(new.raw_user_meta_data->>'faculty_id','')::uuid)
  on conflict(id) do update set email=excluded.email;
  return new;
end $$;

drop function if exists public.update_own_profile(text,text,text,text,text);
create function public.update_own_profile(new_full_name text,new_phone text,new_region text,new_university_id uuid,new_faculty_id uuid,new_language text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if length(trim(new_full_name))<2 or new_language not in('sr','en') then raise exception 'Invalid profile'; end if;
  if new_faculty_id is not null and not exists(select 1 from public.faculties where id=new_faculty_id and university_id=new_university_id and active) then raise exception 'Faculty does not belong to selected university'; end if;
  update public.profiles set full_name=trim(new_full_name),phone_number=nullif(trim(new_phone),''),assigned_region=nullif(trim(new_region),''),university_id=new_university_id,faculty_id=new_faculty_id,faculty=(select name_sr from public.faculties where id=new_faculty_id),preferred_language=new_language where id=auth.uid();
end $$;
revoke all on function public.update_own_profile(text,text,text,uuid,uuid,text) from public; grant execute on function public.update_own_profile(text,text,text,uuid,uuid,text) to authenticated;
